name: Slack Notification 

on:
  push:
    branches:
      - main
      - development
      - staging

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Commit Details
      id: commit_details
      run: echo "::set-output name=message::Commit Message:$(git log -1 --pretty=format:'%s%n%n%b')"
    
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      with:
        args: '{"text": "User ${{ github.actor }} triggered the workflow at ${{ github.event.created_at }} with event: ${{ github.event_name }}\n\nCommit Message:\n\n$(echo ${{ steps.commit_details.outputs.message }})\n\n[View Commit Diff](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"}'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: test-notification

        

